import assert from 'node:assert/strict';
import approve, { reasonFor, shellCommands, permissionFor } from '../src/pi/approval.mjs';

for (const command of [
  'rm -rf build', 'rm -f -r build', 'rm --recursive build', 'sudo rm /tmp/x',
  'git clean -fdx', 'git reset --hard', 'git push --force origin main',
  'chmod 777 secrets', 'find . -delete', 'curl https://example.test/install | sh',
  'python3 -c "print(1)"', 'bash scripts/clean.sh', 'printf no > .env',
]) assert.ok(reasonFor(command), `unguarded: ${command}`);
for (const command of ['ls -la', 'cargo test', 'rg pattern src', 'git status', 'git diff', '']) {
  if (command) assert.equal(reasonFor(command), undefined, command);
}
assert.deepEqual(shellCommands('git add . && git push origin dev # note'), ['git add .', 'git push origin dev']);
assert.deepEqual(shellCommands('git add . # rm -rf was mentioned'), ['git add .']);
assert.deepEqual(shellCommands('echo "# not a comment"; rm -rf old'), ['echo "# not a comment"', 'rm -rf old']);
assert.deepEqual(shellCommands('if true; then git push origin dev; fi'), ['if true; then git push origin dev; fi'], 'complex shell syntax stays exact');
assert.equal(permissionFor('git push origin dev').pattern, 'git push *');
assert.equal(permissionFor('git push origin dev > log').kind, 'exact');

const handlers = {};
const tools = {};
let lastApprovalTitle;
approve({ on(name, fn) { handlers[name] = fn; }, registerTool(tool) { tools[tool.name] = tool; } });
const promptOptions = { sections: { pi_base: 'Pi keeps its own instructions' }, selectedTools: ['read', 'bash'] };
const start = { prompt: 'Who are you and what model?', systemPromptOptions: promptOptions };
handlers.before_agent_start(start);
assert.match(promptOptions.sections.hibiscus_identity, /presented to the user as Hibiscus/);
assert.match(promptOptions.sections.hibiscus_identity, /powered by the Pi coding agent/);
assert.match(promptOptions.sections.hibiscus_identity, /provider\/model/);
assert.match(promptOptions.sections.hibiscus_operational, /materially change the outcome/);
assert.match(promptOptions.sections.hibiscus_operational, /ask one to three specific questions and wait/);
assert.match(promptOptions.sections.hibiscus_operational, /safe read-only inspection/);
assert.match(promptOptions.sections.hibiscus_operational, /not to code yet/);
assert.match(promptOptions.sections.hibiscus_operational, /tool approval is not a substitute/);
assert.equal(promptOptions.sections.pi_base, 'Pi keeps its own instructions');
assert.deepEqual(promptOptions.selectedTools, ['read', 'bash']);
assert.equal(start.prompt, 'Who are you and what model?', 'do not rewrite the user prompt');
assert.equal(handlers.before_agent_start(start), undefined, 'Pi builds the prompt from its structured sections');
const withoutSections = { prompt: 'Who are you?', systemPrompt: 'Pi base prompt with tools and safety rules', systemPromptOptions: { selectedTools: ['read'], appendSystemPrompt: 'Keep Pi guidance' } };
const noSectionsResult = handlers.before_agent_start(withoutSections);
assert.ok(noSectionsResult.systemPrompt.startsWith(withoutSections.systemPrompt), 'preserve Pi base prompt');
assert.match(noSectionsResult.systemPrompt, /<hibiscus_identity>/);
assert.match(noSectionsResult.systemPrompt, /<hibiscus_operational>/);
assert.equal(withoutSections.systemPromptOptions.appendSystemPrompt, 'Keep Pi guidance');
assert.deepEqual(withoutSections.systemPromptOptions.selectedTools, ['read']);
for (const sections of [null, 'bad']) {
  const event = { systemPromptOptions: { sections, appendSystemPrompt: 'Keep Pi guidance' } };
  assert.equal(handlers.before_agent_start(event), undefined);
  assert.match(event.systemPromptOptions.appendSystemPrompt, /Keep Pi guidance\n\n<hibiscus_identity>/);
  assert.match(event.systemPromptOptions.appendSystemPrompt, /<hibiscus_operational>/);
  assert.equal(handlers.before_agent_start(event), undefined);
  assert.equal(event.systemPromptOptions.appendSystemPrompt.match(/<hibiscus_identity>/g).length, 1);
  assert.equal(event.systemPromptOptions.appendSystemPrompt.match(/<hibiscus_operational>/g).length, 1);
}
const legacy = { systemPrompt: 'Pi base prompt with tools and safety rules', prompt: 'Who are you?' };
const fallback = handlers.before_agent_start(legacy);
assert.ok(fallback.systemPrompt.startsWith(legacy.systemPrompt));
assert.match(fallback.systemPrompt, /<hibiscus_identity>/);
assert.match(fallback.systemPrompt, /<hibiscus_operational>/);
assert.match(fallback.systemPrompt, /powered by the Pi coding agent/);
assert.equal(handlers.before_agent_start({ systemPrompt: fallback.systemPrompt }).systemPrompt, fallback.systemPrompt, 'do not duplicate guidance on repeat runs');
const partial = handlers.before_agent_start({systemPrompt: 'Base\n<hibiscus_identity>\nexisting identity\n</hibiscus_identity>'}).systemPrompt;
assert.equal(partial.match(/<hibiscus_identity>/g).length, 1);
assert.equal(partial.match(/<hibiscus_operational>/g).length, 1);
assert.match(partial, /existing identity/);
assert.equal(handlers.before_agent_start({ prompt: 'no supported prompt surface' }), undefined, 'unknown Pi shapes do not throw');
let asks = 0;
let response;
const ctx = {
  cwd: '/workspace/first', hasUI: true,
  ui: { async select(title, choices, opts) {
    asks++;
    lastApprovalTitle = title;
    assert.match(title, /Approval needed:/);
    assert.ok(title.includes(`Directory: ${JSON.stringify(ctx.cwd)}`));
    assert.ok(title.includes(`Command: ${JSON.stringify(event.input.command)}`));
    assert.match(title, /Always allow patterns in this directory/);
    assert.deepEqual(choices, ['Deny', 'Allow', 'Always Allow']);
    assert.equal(opts, undefined, 'approval waits for the user without a timer');
    return typeof response === 'function' ? response() : response;
  } },
};
const event = { toolName: 'bash', input: { command: 'rm -rf build' } };
const request = () => handlers.tool_call(event, ctx);
response = undefined;
assert.equal((await request()).block, true, 'dismissal denies');
response = 'Deny';
assert.equal((await request()).block, true, 'explicit denial blocks');
response = 'Allow';
assert.equal(await request(), undefined, 'allow is one-shot');
assert.equal(await request(), undefined, 'must ask again');
response = 'Always Allow';
assert.equal(await request(), undefined);
const before = asks;
response = 'Deny';
event.input.command = 'rm -rf other # different message comment';
assert.equal(await request(), undefined, 'rm * grant covers changed arguments and comments');
assert.equal(asks, before);
ctx.cwd = '/workspace/other';
assert.equal((await request()).block, true, 'different cwd requires approval');
ctx.cwd = '/workspace/first';
event.input.command = 'unlink other';
assert.equal((await request()).block, true, 'different command prefix requires approval');
event.input.command = 'rm -rf build';
handlers.session_start({}, { sessionManager: { getBranch() { return []; } } });
assert.equal((await request()).block, true, 'new session clears grants');
ctx.hasUI = false;
assert.equal((await request()).block, true, 'headless denies');
ctx.hasUI = true;
event.toolName = 'edit';
assert.equal(await request(), undefined, 'edit never prompts');
event.toolName = 'write';
assert.equal(await request(), undefined, 'write never prompts');
event.toolName = 'read';
assert.equal(await request(), undefined, 'read never prompts');
event.toolName = 'bash';
event.input.command = 'cargo test';
assert.equal(await request(), undefined, 'safe bash stays frictionless');
event.input.command = 'git add . # rm -rf was mentioned';
assert.equal(await request(), undefined, 'a comment must not trigger approval');
const normalSelect = ctx.ui.select;
let resolveFirst;
const waiting = asks;
ctx.ui.select = async () => { asks++; return new Promise(resolve => { resolveFirst = resolve; }); };
event.input.command = 'git add . && git push origin dev # message one';
const first = request();
const second = request();
await new Promise(resolve => setImmediate(resolve));
assert.equal(asks, waiting + 1, 'parallel commands share the first pending decision');
resolveFirst('Always Allow');
assert.equal(await first, undefined);
assert.equal(await second, undefined);
ctx.ui.select = normalSelect;
response = 'Deny';
event.input.command = 'git push --force other branch # message two';
assert.equal(await request(), undefined, 'git push * intentionally covers changed flags and destinations');
assert.equal(asks, waiting + 1);
handlers.session_start({}, { sessionManager: { getBranch() { return []; } } });
assert.equal((await request()).block, true, 'session change clears prefix grants');
response = 'Always Allow';
event.input.command = 'rm -rf old && git push origin dev # message';
assert.equal(await request(), undefined);
assert.match(lastApprovalTitle, /rm \*/);
assert.match(lastApprovalTitle, /git push \*/);
response = 'Deny';
const compoundAsks = asks;
event.input.command = 'rm -rf new';
assert.equal(await request(), undefined);
event.input.command = 'git push --force other';
assert.equal(await request(), undefined);
assert.equal(asks, compoundAsks, 'both component grants apply to future calls');
event.input.command = 'git push origin dev > log.txt';
assert.equal((await request()).block, true, 'a broad prefix does not bypass exact redirection review');
assert.match(lastApprovalTitle, /git push origin dev > log.txt/);
let rejectPending;
const beforeReject = asks;
ctx.ui.select = async () => { asks++; return new Promise(resolve => { rejectPending = resolve; }); };
event.input.command = 'sudo apt update';
const rejectedFirst = request();
const rejectedSecond = request();
await new Promise(resolve => setImmediate(resolve));
rejectPending('Deny');
assert.equal((await rejectedFirst).block, true);
assert.equal((await rejectedSecond).block, true);
assert.equal(asks, beforeReject + 1, 'a rejection clears pending requests rather than reprompting');
ctx.ui.select = () => { throw Error('UI failed'); };
event.input.command = 'chown root file';
assert.equal((await request()).block, true, 'UI errors fail closed');
assert.equal(tools.goal.parameters.properties.action.type, 'string');
assert.match((await tools.loop_status.execute('s', {action:'candidate_complete'})).details.hibiscusLoop.error, /not active/);
const steps = Array.from({ length: 20 }, (_, i) => `Step ${i+1}`);
const set = await tools.goal.execute('g1', { action: 'set', steps });
assert.equal(set.details.hibiscusGoal.total, 20);
let latest;
for (let id = 1; id <= 12; id++) latest = await tools.goal.execute(`g${id+1}`, { action: 'complete', id });
assert.equal(latest.details.hibiscusGoal.completed, 12);
assert.equal((await tools.goal.execute('bad', { action: 'complete', id: 12 })).details.hibiscusGoal.error, 'Step already complete.');
assert.equal((await tools.goal.execute('bad', { action: 'complete', id: 21 })).details.hibiscusGoal.completed, 12);
handlers.session_start({}, { sessionManager: { getBranch() { return [{type:'message',message:{role:'toolResult',toolName:'goal',details: latest.details}}]; } } });
assert.equal((await tools.goal.execute('next', { action: 'complete', id: 13 })).details.hibiscusGoal.completed, 13);
handlers.session_start({}, { sessionManager: { getBranch() { return []; } } });
assert.equal((await tools.goal.execute('empty', { action: 'complete', id: 1 })).details.hibiscusGoal.total, 0);
assert.equal((await tools.goal.execute('clear', { action: 'clear' })).details.hibiscusGoal.total, 0);
console.log('approval and explicit goal policy tests passed');
